# Generated by Django 4.1.2 on 2022-12-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='write description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
